name: "build and deploy docs"

on:
    push:
      branches: [main]
      paths:
        - "**.rs"
        - ".github/workflows/docs.yml"
    pull_request:
      branches: [main]
      paths:
        - "**.rs"
        - ".github/workflows/docs.yml"
    release:
      types: [created]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "build docs"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rust-src
    
      - name: build docs
        run: |
          cargo +nightly doc -Z build-std=core,compiler_builtins --target targets/i686-unknown-none.json
        
      - name: add redirect
        run: echo '<meta http-equiv="refresh" content="0;url=kernel/index.html">' > target/i686-unknown-none/doc/kernel/index.html

      - name: list contents
        run: ls -R target/i686-unknown-none/doc/kernel

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          path: ./target/i686-unknown-none/doc/kernel
          name: "docs"
          if-no-files-found: error

  deploy:
        needs: build
        name: "deploy docs"
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.pages.outputs.page_url }}

        steps:
          - name: Download docs
            uses: actions/download-artifact@v4
            with:
              name: "docs"

          - name: Deploy documentation
            id: pages
            uses: actions/deploy-pages@v2
            with:
              artifact_name: "docs"
